### ISSUE TITLE
Many dutch translations are gone

### ISSUE THREAD

**Issue by mjanssens** [Amebis/eduVPN#100]
In client version 1.0.22 and 1.0.23 a lot of the dutch translations are gone. I could notice that in the main application screen.
I think it has to do with commit 4b3f4229c900d95ef56424214ed0c6ba086a06fe
Several strings were replaced from <fieldname> to <fieldname2> 
Are these automatically imported from transifex?

For completeness I tested also with version 1.0.24, but as expected has the same result

**Comment by rozmansi** [comment]
Thank you for reporting this. Your feedback is appreciated.

The translations were imported from Transifex (manually, not automatically), but after reviewing changes, no translation got lost by the import.

The true cause is @fkooman and I made some UI texts rephrasing a while ago (that's why `SelfUpdatePopupMessage` string ID changed to `SelfUpdatePopupMessage2` etc.). I forgot to remind François to re-translate new texts to Dutch.

While Françis being busy and I don't speak Dutch, would there be a chance you might have time to translate the missing texts on Transifex, please? We don't need them all - resources are ordered by priority and we need only the most important ones. Furthermore, Transifex's translation memory still has translations of old texts to assist you when translating new texts that changed only a bit.

**Comment by fkooman** [comment]
I updated some translations just now, not sure if those are the ones you were talking about. Transifex is horribly slow, not really usable on my laptop.

**Comment by mjanssens** [comment]
I would be happy to help you out with the Dutch translations. This week I will find time for that.
As a sidenote, if you aren't happy with Transifex you could also try Crowdin.
Both work, I have some translation experiences from the Nextcloud project. They are fortunate to have several regular translators. Would be great to have that on this project too, if my guess is right that a lot more languages will be added in the future.

**Comment by rozmansi** [comment]
@mjanssens, that is awesome - thank you. Please, click _Help Translate "eduVPN"_ button in the upper right on [eduVPN@Transifex](https://www.transifex.com/amebis/eduvpn/).

@fkooman, sorry to hear about your experience with Transifex. I don't have any speed related issues with their website, but that could be very subjective. Slovenian is all translated and I only need to update a string or two now and then. Could have turned into the same nightmare if I needed to translate hundreds of strings in a run.

If it would make translating more appealing and attract more volunteer translators, I am totally in for migrating the translation project someplace else.

**Comment by rozmansi** [comment]
BTW, @fkooman's translations should be sufficient to reestablish the Dutch UI. However, I'd keep this issue open for a week or two and publish a new release after @mjanssens' contribution.

**Comment by mjanssens** [comment]
@rozmansi or @fkooman, I've made a request on Transifex for joining as a translator, so someone has to authorize me before I can view or edit translations.

**Comment by rozmansi** [comment]
Done

**Comment by mjanssens** [comment]
Dutch translations done

**Comment by fkooman** [comment]
Thanks so much! :1st_place_medal:
