### ISSUE TITLE
Profile selection is not used-friendly

### ISSUE THREAD

**Issue by LongmanU** [Amebis/eduVPN#137]
Hi,
we are introducing eduVPN at the University of Osnabrueck in Germany, and I see problems in setting up the windows client: Users are not aware, that the profile entry can (and should) be clicked. I more looks like a description, and they try to click "University of Osnabrueck" instead of the specific profile below. Perhaps the profiles could be formatted/designed so that it is more clearly, that they can be clicked.
Thanks,
Marc Langer

**Comment by fkooman** [comment]
Screenshot of the situation: 
![image](https://user-images.githubusercontent.com/616885/78338242-af99f900-7592-11ea-8c55-77c13b47fb72.png)

**Comment by LongmanU** [comment]
In our situation even worse, as we only have one profile:

![image](https://user-images.githubusercontent.com/24946484/78338507-37800300-7593-11ea-81ed-3abf3c1a2c28.png)

**Comment by rozmansi** [comment]
Thanks for reporting this.

This is what happens when an application introduces own design rather than sticking to the recommended OS-default styling. It looks nice, but people less inclined towards learning new tricks get annoyed.

However, the list items do react with a background change on mouse hover - which any normal non-clickable text doesn't. Unfortunately, not applicable to touch screens.

I have two suggestions to mitigate this issue:

1. Change mouse cursor to hand when hovering over the clickable list item - again not applicable to touch screens. This one should be implemented anyway.

2. Change the colouring, so all the clickable texts use a distinct colour. Not the "eduVPN" cyan which is also used by titles thou. Maybe grey. Or, grey&bold.

There is a major UX redesign pending (#135). Will apply my suggestions there and see how it looks like.

**Comment by rozmansi** [comment]
The GUI was completely redesigned, and the clickable list items should now be more obvious:
![image](https://user-images.githubusercontent.com/6889694/102686689-85a06980-41e9-11eb-9159-063f15758936.png)
![image](https://user-images.githubusercontent.com/6889694/102686696-93ee8580-41e9-11eb-98b3-b9bdd5ea8d11.png)
