### ISSUE TITLE
stay connected when going through the UI

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#14]
if you leave the "VPN Connection" window (e.g. going back) without pressing disconnect it will disconnect anyway.

**Comment by rozmansi** [comment]
This issue was initially reported by Rogier. I plan to fix it after issue #12 is fixed. I estimate I'll have a cleaner shot there.

**Comment by rozmansi** [comment]
OK, I got #12 sorted out, now this one... But, before I fix it, I'd like to know, what is the expected behaviour.

Clicking (<) Back button can leave the connection active. I suppose the connection should be left active until a new one is selected/configured to connect to, right?

If so, how can the user get back to the status page of the active connection then? Clicking exactly the same one on the list of connection history? The GUI had a button planned for this a long time ago:
![3-connections.png](https://github.com/eduvpn/documentation/blob/master/app/windows/3-connections.png)
But newer GUI design removed that button.

**Comment by fkooman** [comment]
I'm not really sure about the UI part, but what makes sense to me is that the VPN that is currently connected stays connected until a new connection is started. Navigating through the UI should not have any effect on active VPNs (unless disconnect is presses). Maybe a button or a "statusbar" might be an option, don't know. @sveeke

**Comment by sveeke** [comment]
The disconnect behaviour bothered me in the app too. And indeed, in the first version of this styling I made buttons for it. But people wanted to get rid of buttons, so version 2 of the styling was born. I think best is to have two option to get back to the active connection screen:

1) Right click on the green eduVPN icon in the taskbar tray and click something like 'Connection' or 'Status'.

2) Press the same profile button in the 'Connect' screen you are connected too. 
Question to @rozmansi Are there ways of giving the connected profile entry on the Connect screen some sort of highlight so that it is clear to users what the current connected profile is? I think that would be a cool/clear way of showing it to users :).

By the way, on mobile operating systems this is a bit easier because the running VPN connection is also part of the notification bar.
