### ISSUE TITLE
Win-10 64-bit After choosing the wrong country it is impossible to connect to another

### ISSUE THREAD

**Issue by stefan863** [Amebis/eduVPN#15]
When choosing a country in the menu, it is impossible to switch to another language after the

>  "waiting for authorization"

 pop-up has appeared. If a user dismisses this message the program keeps trying to connect to the loginportal of the first country and follow errormessage appears:

> "Loading of the profile list failed. Client authorization failed. No access token granted."

 However, if another country is selected after this errormessage the program wil only connect to the first country that was selected

**Comment by rozmansi** [comment]
You are right, the program keeps connecting and getting 401 Unauthorized:
![capture1](https://user-images.githubusercontent.com/6889694/29812961-b3d041e4-8ca8-11e7-8708-44a9a70b8841.png)
![capture2](https://user-images.githubusercontent.com/6889694/29812960-b3c5af4a-8ca8-11e7-89c7-842d7a742117.png)

You need to click the (<) _Back_ button to select the authenticating country again. But hey, there is a bug in the client that clicking (<) takes you back to the initial page instead of authenticating country one.

**Comment by rozmansi** [comment]
I was thinking about this... If @stefan863 got confused in the wizard, imagine the confusion the ordinary users might have. This clearly demonstrates a poor UX.

Change the flow so that an authentication is performed earlier: immediately after the user clicks the authenticating instance (country) and before wizard continues to the connecting instance/profile selection page.
