### ISSUE TITLE
eduVPN 2.0 - forget secure internet allignment

### ISSUE THREAD

**Issue by efef** [Amebis/eduVPN#165]
In 2.0 client version, when try to remove configuration, for "secure internet" I need to do right-mouse on "location" instead of country-flag. 
For "other server" is works as expected, right-mouse on hostname. 
![Screenshot 2021-06-18 at 11 27 53](https://user-images.githubusercontent.com/3393474/122539781-4633c800-d028-11eb-852d-978659566940.png)

**Comment by rozmansi** [comment]
The context menu is now attached to secure internet server "list" (it is a list, but it always contains only one single entry), and _Change Location_ button as before.

I have no idea how and why, but the issue with the Tab traversing controls present about a year ago that influenced my decision to attach context menu to the button rather than the list, is not present any more. Well, a lot of things changed since and one of them must have fixed this issue not to reappear any more.
