### ISSUE TITLE
add other address / instance

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#17]
Some idea:

1. maybe assume `https://` when only a host name is provided;
2. do only accept host names as input and force them to be https;

Also, the name of the button "add other address" and "other instance" is not consistent...

**Comment by rozmansi** [comment]
@fkooman, I'd vote for "1." because:

- The "2." prevents having multiple discovery files hosted on the same host.
- The "Add other address" feature is intended for professionals only. Hypothetically: While preparing a new eduVPN instance it might be welcome to have the `info.json` file on your desktop and use `file://C:/Users/Simon/Desktop` address.

If the eduVPN instances are _always_ bound to the exactly one host = absolute `https://host/` URI - not allowing multiple instances like `https://host/` and `https://host/dev/` on the same host - then I agree the "2." option is better. Akin SMTP/POP3/IMAP experience.
