### ISSUE TITLE
uninstall Let's Connect! gives wintun error

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#176]
It does seem the uninstall (of Let's Connect! 2.1) completes successfully after clicking "OK".

(This system also has eduVPN 2.1 installed).

![image](https://user-images.githubusercontent.com/616885/135873838-b4f998ba-ffec-4193-911c-4b6b335b2a15.png)

**Comment by rozmansi** [comment]
This issue was discussed elsewhere. To recap: if eduVPN client is installed while Let's Connect client is uninstalled (or vice versa), the uninstall won't be able to uninstall the Wintun driver, because the other client still needs it. Unfortunately, this is displayed as an error. Fortunately, harmless once dismissed.

With the `wintun.dll` v0.14 and above, this should no longer happen. It is bundled in OpenVPN 2.5.4-20211202, released with eduVPN Client 2.1.1.
