### ISSUE TITLE
support arm64/aarch64

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#180]
More systems have ARM CPUs these days. It would be nice to also support eduVPN/Let's Connect! on ARM64 for Windows >= 10.

**Comment by rozmansi** [comment]
I already have a working solution for this. Unfortunately, Microsoft does not deploy Visual C++ RTL as an .msm installer merge module for ARM64. Only x86 and x64 (for the time being). The eduEd25519.dll must use dynamic RTL (requirement of the `/clr` MSVC flag), the rest of the binaries could be compiled to use static RTL. So, we cannot drop the Visual C++ RTL requirement. However, there is an .exe installer for the Visual C++ RTL libraries. Probably, I'll end up switching from .msm to .exe installer. This would need testing the upgrading from 1.x and 2.x works correctly. Furthermore, organizations deploying eduVPN Client using .msi files (Group Policy on managed laptops), would need to deploy/install RTL .exe before deploying eduVPN Client.
Maybe use .exe RTL installer for ARM64 only, and leave x86/x64 as is?

**Comment by fkooman** [comment]
Perhaps you can find a replacement for your current ed25519 library that works without visual c++ stuff?  It is very few lines of code anyway...

**Comment by rozmansi** [comment]
The eduEd25519.dll is only a thin wrapper to bridge the libsodium.lib and .NET Framework. I totally forgot that the eduEd25519.dll  is actually x86 on ARM64 (.NET Framework imposed limitation). So, it actually gets the RTL it requires from x86 .msm. All fine here.

It's the OpenVPN that is upstream configured to use dynamic RTL when build with vcpkg/MSVC that is adding missing ARM64 .msm dependency. Fortunately, I was able to reconfigure OpenVPN to use the static RTL. So, we get back the OpenVPN binaries using static RTL as it was the case in the good old MinGW build environment.

**Comment by rozmansi** [comment]
Drat... It turned out that OpenSSL always compiles using dynamic RTL when producing libcrypto-1_1.dll and libssl-1_1.dll. This resulted in openvpn.exe, libpkcs11-helper-1.dll and lzo2.dll correctly using linked-in static RTL, while OpenSSL .dlls still depended on vc_redist.

It took me a few hours to reconfigure the vcpkg/OpenVPN build system to link *everything* statically. This means it's just one openvpn.exe binary now. No satellite .dlls. (Except for the wintun.dll, which is shipped as DLL only.)

Apart from finally liberating OpenVPN from the dreaded vc_redist dependency, the linker optimization removed all the dead code. The resulting openvpn.exe+openvpnserv.exe are actually shorter than old .exes and .dlls combined. 3.88 MB reduced to 2.79 MB.
