### ISSUE TITLE
Notification on session expiry

### ISSUE THREAD

**Issue by fritterhoff** [Amebis/eduVPN#184]
At the moment the session runs e.g. for 3 days and gets terminated silently without any previous notification. 

I would suggest some notification e.g. 15 minutes before session timeout and maybe one on the actual disconnect. In the last months, disconnects without any notification caused some confusing on my side when running an SSH session or copying some larger files.

**Comment by rozmansi** [comment]
Sounds reasonable suggestion. Will introduce it for the 2.2 release.

**Comment by rozmansi** [comment]
Actually, session expiration and disconnection notifications were introduced in v2.0. They are displayed as a balloon on the systray:
![image](https://user-images.githubusercontent.com/6889694/148560474-39deda24-808e-4df2-93d0-a1a6698635e3.png)

However, Windows ignores our message timeout hint. It was set for 5 seconds, but increasing that value doesn't appear to make any difference. Windows trims the message display time according to the user's accessibility settings.

After 5 seconds, the message is moved to the notification area:
![image](https://user-images.githubusercontent.com/6889694/148561104-cf8d69ee-f0f4-4cc6-8a0a-6f84a51d1371.png)

The same type of notification is used when eduVPN disconnects (manually or due to session expiration):
![image](https://user-images.githubusercontent.com/6889694/148561257-2622203f-520e-4c32-a36f-c887770cdbe6.png)

Maybe, you were away from your computer (while your computer was copying some larger files) and just missed those notifications.

Will discuss with our team if we can make expiration notification a system modal dialog box.

**Comment by fritterhoff** [comment]
Neither me nor any fried of me has ever seen such a hint. Atm I'm using 2.1.0
![grafik](https://user-images.githubusercontent.com/32478819/148561786-c63a005c-3d8f-4576-82df-1900d8a572ff.png)

**Comment by fritterhoff** [comment]
Ah wait a second... seems like that was a Windows config issue in my case. Maybe my friends have done smth. else wrong.

**Comment by rozmansi** [comment]
Thanks for your feedback.
