### ISSUE TITLE
delete user data on uninstall / document how to do that

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#187]
it would be nice when a users uninstalls the application they have the option to fully delete the application data (certificates, oauth tokens, ...). Maybe it should not even be an option, and it should be the default...

Another option: have a "Reset app data" button on the settings page that would delete all data and restart the app.

If that is too complicated, perhaps it is possible to document how to manually delete all data.

We notice some users assume that uninstalling and installing the eduVPN application again would result in a 'clean slate', which is not the case.

**Comment by rozmansi** [comment]
> it would be nice when a users uninstalls the application they have the option to fully delete the application data (certificates, oauth tokens, ...). Maybe it should not even be an option, and it should be the default...

The installer only takes care of _application_ data. The application data belongs to software vendor.

The _user_ data is managed by the client executable itself. The user data belongs to user.

It is usual practice on Windows (and Linux too), that application uninstall removes only application data, while user data in user home folder (`C:\Users\user` or `/home/user`) remains. So, just following the usual UX here.

Sorry, I couldn't help myself to have this introduction, as this feature request is not something I believe we should pursue in installer.

Nevertheless, here are the technical details about implementing options you proposed:

1. Making the user data purge optional would require WiX installer bundle redesign to include a checkbox. I have found an online tutorial how to do this. So, this should be doable.

2. Having installer do this always, would require reverting d21aef631450b6a73f0f378909c30b1bcb0261d4. Otherwise, user data gets killed on every update too. But that would make 2.1 no longer upgradable to the new releases. Viable only after 2.1 is sunset and 2.2 is deployed worldwide.

> Another option: have a "Reset app data" button on the settings page that would delete all data and restart the app.

3. This is doable quite easy. Is this common enough problem users have with the client to justify cluttering Settings page in the app?

> If that is too complicated, perhaps it is possible to document how to manually delete all data.

4. It's simple: close the client and run `rd /s "%LOCALAPPDATA%\SURF"`

Let me know.

**Comment by fkooman** [comment]
Another item for the FAQ: how to remove an existing server.
