### ISSUE TITLE
Allow deleting providers/profiles

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#20]
It seems not possible to delete anything at the moment.

**Comment by rozmansi** [comment]
No, indeed it is not. However, I have implemented some scoring scheme to sort most used profiles on top of the list.

There is not much space in GUI for a "Remove" button available. To keep the GUI touch-screen friendly, I suggest the following approach: if user push-and-hold the profile for 3 seconds a menu would pop-up with a "Forget" option.

**Comment by fkooman** [comment]
> if user push-and-hold the profile for 3 seconds a menu would pop-up with a "Forget" option.

does that work with a mouse as well? or would right click be more appropriate there?

would deleting a profile remove the stored certificate as well?

**Comment by rozmansi** [comment]
I have added a right-click pop-up menu with "Forget" option.

However, this is not working yet. The problem is the "select list item to continue" GUI philosophy. As soon as you right-click the configuration on the list, the framework marks the configuration as _selected_, triggering immediate connecting.

A distinction between "select to continue" and "select to pop-up additional options" has to be implemented.

**Comment by rozmansi** [comment]
This issue was resolved finally by the 381f6ac0cc00cd56dc487e88d93efd205f63f374.

Right-click (or use SHIFT+F10) to pop up a menu for selected configuration. The menu will display _Forget_ option. This removes the selected configuration entry from history. However, it does not remove associated access tokens, nor cached certificates.

The issue with client certificate mismatch (#21) shall be resolved separately.
