### ISSUE TITLE
Windows client error after upgrading to eduVPN V3

### ISSUE THREAD

**Issue by mkoelewijn** [Amebis/eduVPN#217]
When upgrading to eduVPN 3 the windows client get the following error when a reauthorisation is triggered in the browser. Maybe the app seems to forget to refresh  /.well-known/vpn-user-portal (to the new used /portal) ?

Deleting the profile and adding the profile again did not help, i needed to restart the eduVPN app to make it work again.

![image](https://user-images.githubusercontent.com/26085443/215263132-b22f4914-4424-4e22-9058-42af392bf21d.png)

**Comment by rozmansi** [comment]
Sorry, but I am afraid this issue is not related to the eduVPN client for Windows:

The client is not referencing the URL from the screenshot `/_oauth/authorize` anywhere. The screenshot indicates the error occurred in the web browser. Maybe on the user portal or OAuth somewhere. I believe this is a server-side issue. Might as well be a browser cache issue?

**Comment by rozmansi** [comment]
Checked the client code, and it appears it is not caching `.well-known/vpn-user-portal` replies. It also sets caching policy to `HttpRequestCacheLevel.NoCacheNoStore`, so .NET Framework or proxy shouldn't cache it either.

**Comment by rozmansi** [comment]
After consulting François, I believe I found the cause of this issue: client is caching `/.well-known/vpn-user-portal` content after all - in memory.

Initially, I misunderstood the issue appears after upgrading eduVPN *client* to v3, where in fact it's the eduVPN *server* that is being updated to v3.
