### ISSUE TITLE
winget uses preview version

### ISSUE THREAD

**Issue by Silther** [Amebis/eduVPN#237]
if you use winget to install the app it uses the preview version (3.25x) instead of the stable 3.5 version

**Comment by rozmansi** [comment]
True.

winget publishing is not an official way to install eduVPN. See: https://app.eduvpn.org/.

Initially winget was used to deliver non-pre releases indeed. However, I pushed this 3.255.8 (4.0-pre8) version on the winget, because it contained important fixes and because I anticipated the powers-that-be would soon grant permission to release 4.0. So the window winget repo would be on the pre-release channel was planned to be short. Unfortunately, it cannot revert versions backward.

The winget will get back to the release channel after 4.0 is released. And hopefully stay there.
