### ISSUE TITLE
Settings button while adding new profile

### ISSUE THREAD

**Issue by mkoelewijn** [Amebis/eduVPN#26]
When adding a new profile you can also go to the settings. Since the settings are applied globally it can be confusing to the user so its better to only display the settings button on the home screen.

<img width="316" alt="screen shot 2017-10-04 at 14 25 32" src="https://user-images.githubusercontent.com/26085443/31178733-3cce2eec-a91a-11e7-91fd-0bd5f24573ae.png">

**Comment by rozmansi** [comment]
Actually, the settings button there is intentional. It allows the user to configure the client _before_ connecting. You see, clicking on "NW Testbed" above would start connecting immediately. Especially, this might be important on the first run when the "home" screen has not been presented to the user yet.

If you want to sacrifice user's ability to configure-before-connect, I can remove that button. No hassle.

Please, rethink and let me know. :)

P.S.: There's also a bit hidden shortcut to the settings page that works regardless the current wizard page. Right-click on the eduVPN icon in the system tray and choose "Settings" in the pop-up menu. Knowing this might really make the settings button mentioned above obsolete.

**Comment by mkoelewijn** [comment]
OK, i didn't look at it that way. We should keep it like this then. Closed
