### ISSUE TITLE
[discuss] allow multiple connections simultaniously

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#29]
Suppose you want to connect to a "Secure Internet" VPN (for the default gateway) and also to a "Institute Access" VPN for just a few destination IP ranges, it makes sense to allow multiple connections at the same time through the eduVPN app.

**Comment by rozmansi** [comment]
While this could be done in the eduVPN client, there are some OpenVPN fundamentals we need to resolve first. Those scenarios should be tested using OpenVPN GUI first, before nose-diving into this feature.

### Multiple TUN/TAP adapters
Each OpenVPN connection requires a separate TUN/TAP adapter. On Windows, the adapters are managed manually. To create one globally, you need to run __elevated__ the following command:
```
"C:\Program Files\TAP-Windows\bin\tapinstall.exe" install "C:\Program Files\TAP-Windows\driver\OemVista.inf" tap0901
```
This creates a new TUN/TAP adapter with some unpredictable name, like "Network Connection 2" or "Ethernet 3". Created adapter persists across restarts and must be manually uninstalled. This is analogous to `--mktun` and `--rmtun` on Linux.

Thus, somebody with administrative privileges (could even be the installer process) needs to create in advance as much TUN/TAP adapters as the number of concurrent connections the client will ever run.

On Linux, this is much simpler, as OpenVPN can create `/dev/tunXX` or `/dev/tapXX` on demand. And clean them up after disconnected.

We could create TUN/TAP adapters on demand on Windows, but we need to introduce a system service to do this for the end user. eduVPN client runs non-elevated.

### Order of connecting
I am running multiple OpenVPN connections daily, but I haven't tried mixing "default gateway" and "split tunnel" variants. I run multiple "split tunnel"-s without any issues for years now.

What happens when you have an established split tunnel VPN connection, then the default gateway is changed after connecting to "secure internet" VPN? The effect for the existing split tunnel VPN connection should be about the same as if the laptop would change connection to another network, right?

**Comment by rozmansi** [comment]
This unfortunately didn't make it into v2 UX redesign.
