### ISSUE TITLE
client configuration update requires app restart?

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#37]
I modified the client configuration file that clients obtain through the API, and it does seem to work, but not after disconnect/connect only after application restart. When are the client configurations obtained through the API? Only at application start?

**Comment by fkooman** [comment]
Expected behavior: fetch client configuration just before connecting.

**Comment by rozmansi** [comment]
Client configurations (for OpenVPN) are downloaded on the first connection attempt and are cached in memory thereafter. Thus, they persist between client reconnects, but they do not persist between client restarts, as you have discovered yourself.

The easiest solution would be to remove the caching of connection configurations.

**Comment by fkooman** [comment]
I guess it makes most sense not to have any caching there...

**Comment by fkooman** [comment]
(I haven't checked this for `info.json`, but probably the same applies there...)

**Comment by fkooman** [comment]
It works now without restarting the application, but when the server kicks the client off, e.g. through server restart, the client will try to connect again with the old configuration and thus fail. A manual "disconnect" is required first before obtaining new configuration.

**Comment by rozmansi** [comment]
That's because the openvpn.exe process tries to do the reconnect itself. It probably assumes the line dropped and that it can handle the reconnect itself.

This could be solved by monitoring the openvpn.exe log and when specific entry is recorded the eduVPN client could intervene. Something similar as we do when CA is changed to force client re-request for a new certificate.

But I need your help with that. Can you provide me with the openvpn.exe log of this specific situation, please?
