### ISSUE TITLE
"dev" instances discovery key changed

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#39]
new public key: `zzls4TZTXHEyV3yxaxag1DZw3tSpIdBoaaOjUGH/Rwg=`.

**Comment by rozmansi** [comment]
The "dev" URIs and public keys are not mentioned anywhere in the source tree. Therefore, I cannot update this public key anywhere.

I did get an idea first to add the dev URI and public keys to the `eduVPN.Client.exe.config` file as a comment we could easily switch between release and dev discovery files only by (un)commenting section of configuration files.

However, after giving it a second thought, I don't think it is the best idea to disclose the dev discovery URIs in the config file since dev instances are hosted on your personal servers.

You decide.

**Comment by fkooman** [comment]
They are: https://static.eduvpn.nl/disco/ 

I don't mind if they are listed in the configuration template, normal users won't run into them anyway...
