### ISSUE TITLE
warn if no Internet connection is available when trying to connect to VPN

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#57]

**Comment by rozmansi** [comment]
Generally speaking, I hate to use tests to pre-detect a condition just to block the execution.

I have seen my share of ill-written tests that determined some action cannot be performed, where in reality it could be and would work fine.

The best test is to try it for real then catch & unwind _if_ it fails. Well, we're not talking about jumping in the swimming pool with no prior knowledge of water depth, of course. :)

Since I have yet to find a _reliable_ check if there is an internet connection or not, the eduVPN client cannot warn in advance.

I have added a bit more explicit error description should contacting the eduVPN servers fail:
![img_15122017_134454](https://user-images.githubusercontent.com/6889694/34043292-b709b0fa-e1a0-11e7-9213-11efa9000d00.png)

Funny, if I'd put the word " because " between aggregated exceptions on the list above, the error message would have been a lot more logical:

> Loading of the provider source failed.
> - because -
> Downloading from web failed. Please check your internet connection.
> - because -
> The remote name could not be resolved.
