### ISSUE TITLE
"no items" when no profiles are available is confusing

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#62]
When no profiles are available for a user, either because they lack group membership, or there are simply no profiles the message should be more clear.

Something like "No profiles available" is also not really helpful for the user, it doesn't inform them they need a certain group membership if that is actually the problem.

**Comment by rozmansi** [comment]
This is a generic message when a `<ListBox>` control is empty. I made it because the design omitted control frames which made an awkward feeling of white space when any list appeared empty.

If you can propose a customized message, I shall tweak the profile lists to show it. I also need to tweak the profile list to add an extra internal state: loading vs. finished, not to display a message "No profile available" in the short period of time before the `/profile_list` response is retrieved. The `<ListBox>` has no knowledge is the list not populated yet, or is the list populated but with zero items.

**Comment by fkooman** [comment]
@sveeke

**Comment by rozmansi** [comment]
I reviewed the code and discovered, that lists actually do have three distinguishable internal states already:
1. The list source is `null` = the list is loading.
2. The list source is `ObservableCollection<Profile>` with no elements = the list has loaded, but server returned zero available profiles.
3. The list source is `ObservableCollection<Profile>` with some elements = the list has loaded and there are some profiles available.

So I guess I can just introduce two separate texts: _"Please wait while the list is being populated."_ and _"No profiles are available."_

**Comment by fkooman** [comment]
The portal shows this for users that don't have profiles available for them:

>  No VPN profiles are available for your account.

**Comment by fkooman** [comment]
Another user ran into this problem today.
