### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by sveeke** [Amebis/eduVPN#63]
No idea what went wrong here. I tried to login on the eduVPN Windows Client (kluitje.eduvpn.nl to be specific) with a OneGini-account.

![image](https://user-images.githubusercontent.com/12334213/34204924-cc7012c0-e580-11e7-9e01-dac3739b50fc.png)

`http://127.0.0.1:49318/callback?code=LEx3M8yD2lAk2sDE2AlN9t8rms8OxIrkld6qXO6O6uSgPbMdyrJIpm29oYurHcsTVN_KZsBCzaWxngfJH1pOAHsidHlwZSI6ImF1dGhvcml6YXRpb25fY29kZSIsImF1dGhfa2V5IjoiYTU5MDgxYWM2OGQwNTViYmQxNmVkMWQ0MDZkZTRmODEiLCJ1c2VyX2lkIjoiMTliYWE1ODJhZTgzN2JmMWJkZGRjZWJjNzM0NjRiYjZlNTUxYjYzMyIsImNsaWVudF9pZCI6Im9yZy5lZHV2cG4uYXBwLndpbmRvd3MiLCJzY29wZSI6ImNvbmZpZyIsInJlZGlyZWN0X3VyaSI6Imh0dHA6XC9cLzEyNy4wLjAuMTo0OTMxOFwvY2FsbGJhY2siLCJjb2RlX2NoYWxsZW5nZSI6InZCQi13OUZDU1VYWV9kWGdTemR4SGJRTEdkc3NHcEJ0N2FUMkVaSDVUZ1kiLCJleHBpcmVzX2F0IjoiMjAxNy0xMi0yMCAxMToyODoyMiJ9&state=7xg4WtuIUK3_xTnU2opeUz1U81BN_SJQLyRHXT3f8VE`

**Comment by rozmansi** [comment]
Unfortunately, I was not able to reproduce this problem. The error basically says that in one of the collections some element with the given key/index was not found. But I fail to find in which one. I even implanted your URL in the code flow but it reported that `state` parameter is incorrect (which is expected behaviour).

There's not much else I can do with this particular issue without more information how to reproduce it.

However, I did add a detailed diagnostic output to the error web page in [92123f1dbce3d89d49205cc9da938fa4c7c313f8](https://github.com/Amebis/eduOAuth/commit/92123f1dbce3d89d49205cc9da938fa4c7c313f8):
![image](https://user-images.githubusercontent.com/6889694/34609240-34507e50-f21c-11e7-8c33-b41eb2f73312.png)
![image](https://user-images.githubusercontent.com/6889694/34609258-44d1d65c-f21c-11e7-8a7c-ec0b5b9d2d98.png)

Should this error occur again, it will help me better understand and locate the exact line of failure.

**Comment by fkooman** [comment]
![image](https://user-images.githubusercontent.com/616885/34778057-73d11360-f61c-11e7-8dbf-3d2751686e6c.png)

**Comment by fkooman** [comment]
It seems even though there is this error, the token retrieval does work!

**Comment by rozmansi** [comment]
Drat! :( I forgot to enable full debug info on release builds. Therefore, the release build error reports do not contain the source code line numbers. The release error report just says that "Index out-of-bounds" error occurred somewhere in this particular function.

I have enabled full debug info for all builds in d4583fcdaea00cb86b3689342e8bbfa008d820b6. Since this is an open source project there is no harm to include full debug info in release builds too, providing it will aid in easier troubleshooting at a cost of larger binaries.

Fortunately, I have found the very cause of this issue and fixed it in https://github.com/Amebis/eduOAuth/commit/5cca3d36d006a2e06d75776e6bf6a7f00a1b2e8f.
