### ISSUE TITLE
Combined lay-out issues Let's Connect! client

### ISSUE THREAD

**Issue by sveeke** [Amebis/eduVPN#73]
Ola!

The apps looks great already, but I noticed some things that could be better. I try to combine them in this issue so I won't flood the issue list, but if seperate issues are preferred I'll do that instead :). Just let me know then.

### 1) Icons on VPN Connection screen are not centered.
The shield and profile logo are left alligned, while I would much prefer them to be centered under the 'Status' and 'Provider' texts.

### 2) When Notification is clicked, it stays 'selected'.
When you hover over the notification, it changes its colour (looks more or less 'selected'. I don't know what the use case of this is, since it's a passive one-way notification to users without any interaction right? So as far as I am concerned the hover-on effect can be removed. But that being said, if it serves a purpose then it has some weird behaviour right now. When clicked, it stays 'selected' after that. You can't 'unselect' the notification.

### 3) Very subtle hover-on effect on buttons.
In the VPN Connection screen, the 'View log' and 'Disconnect' buttons change colour slightly when you hover-on with the mouse. This is actually really nice since it offers some control feedback to the user. But the effect is a bit too subtle I think, especially when you have a high contrast screen it's hardly visible. Is it possible to make the effect a bit more noticable?

### 4) Missing hover-on effect on some buttons
Most buttons offer hover-on effect to give users some control feedback (most text buttons, but also the settings button for example). This isn't the case with the profiles you can select and the 'Add another' button. This feels weird to me, it doesn't reassure me as much as the buttons that provide me with feedback. I think adding the hover-on also to these buttons would be great. Also, I think it's fine if 'Add another' has to become a real button with border and stuff in order to do this.

By the way, I like it that when you return to 'Connect' screen while being connected, it shows the green shield there. I didn't include that in my design mockups, but really think that adds something useful :-). Great addition.

**Comment by rozmansi** [comment]
1) Fixed

2) Fixed - I use a standard `<ListBox>` element to display the messages. That's why it behaves like one can focus, select a message on the list, and do something with it. But you can't indeed. I have passivated it by providing an alternate list item styling that does not react to `IsMouseOver` and `IsSelected` states.

3) Fixed - The buttons now completely invert on mouse over. I had to switch from PNG button icons for Secure Internet and Institute Access to vector based, so the icon fill can follow the button text colour and invert on mouse over too.

4) Fixed - Those link buttons already did have some hover effect but for the Let's Connect! theme it might have been too subtle indeed. I have increased the contrast now. Furthermore, the mouse cursor is now changed to hand when over any button or link.
