### ISSUE TITLE
UI leaves not enough space for profile display

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#83]
It would be cool to be able to at least be able to see 3 to 5 profiles without needing to scroll.

@sveeke

![image](https://user-images.githubusercontent.com/616885/37837552-c8fc833e-2eb5-11e8-843c-d8ae335679ae.png)

**Comment by rozmansi** [comment]
I can reduce control padding a bit. Unfortunately, it will soon make UI look crammed.

I remember, I removed the custom styling from the main frame temporarily once. This allowed standard Microsoft Windows resizing, maximizing, minimizing of the client window... Boy, it looked and felt good to have some proper sized screen real estate. :)

**Comment by fkooman** [comment]
I'd be all for it! Let it breath! :)

**Comment by fkooman** [comment]
@sveeke does not have time to look at it...

For now you can increase the window (default size) at your discretion. It would be nice if Secure Internet + Institute Access VPN provider with 5 profiles do not require scrolling...

**Comment by sveeke** [comment]
I don't have time today, but I just read up on this. I agree that there should be more buttons visible. Looking at a solution:

1) Partly the fonts turned out bigger in the app than they were intended, so maybe they can be made a bit smaller.

2) The app can be a bit larger, but I don't feel like making it an office- or browser-like app since screen filling apps hardly exist anymore on Windows. And with good reason, maximizing should only be possible when it's really useful/has a clear purpose. Our app (90% of common apps actually) doesn't provide the user with enough use cases and information to warrant a full screen 1920x1080 application... Not even halfscreen. I have never seen any VPN application that warrants (or offers for that matter) this.

I was thinking of making a new styling for desktop operating systems, since they can be (a lot) larger than their mobile counterparts. The Windows app is rather small now because it is based on the same design as Android, since that would have been the easiest route (one styling for all apps), but I agree it is too cramped. I can maybe create some time tomorrow so if any of you have suggestions let me know.

3) The buttons are really huge as of now, I think they can be smaller :-).
